# Generated by Django 5.0.7 on 2024-07-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='descripcion',
            field=models.TextField(default='sin_descripcion'),
        ),
        migrations.AddField(
            model_name='category',
            name='nombre',
            field=models.CharField(default='sin_categoria', max_length=100),
        ),
    ]
