# Generated by Django 5.0.7 on 2024-07-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_name_category_descripcion_and_more'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='sin_color', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='descripcion',
            field=models.CharField(default='Descripción no disponible', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje', max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='imagen',
            field=models.ImageField(default='imagenes/default.jpg', upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.CharField(default='00000000', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.CharField(default='sin_marca', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(default='sin_material', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='nombre',
            field=models.CharField(default='sin_nombre', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='precio_desc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='smart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_articulo',
            field=models.CharField(default='sin_tipo', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='default-url', max_length=100),
        ),
    ]
