# Generated by Django 5.0.7 on 2024-07-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_category_remove_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
