# Generated by Django 5.0.7 on 2024-07-13 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_name_category_descripcion_and_more'),
        ('items', '0003_alter_item_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_items', to='category.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo_articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_articulo_items', to='category.category'),
        ),
    ]
